### ISSUE TITLE
Option to override deprecation date

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/ec2imgutils#80]
An image may need to be deprecated after the fact. For this use case it would be nice to have an option to override the deprecation date so it matches the correct time of deprecation.

**Comment by smarlowucf** [comment]
The format we use is YYYYMMDD so it would be helpful to have an option like `--deprecation-date 20220202`. This would override the default which is the current date.

**Comment by rjschwei** [comment]
Agreed @apozsuse this is low hanging fruit to get you started could you please take a look? Please let me know if you have any questions.

**Comment by apozsuse** [comment]
Hi,

you can find the PR [here](https://github.com/SUSE-Enceladus/ec2imgutils/pull/82)

I was not able to test the locally built package in SLES 12 SP5 because out of the box there's no package to provide python3-boto3.

May be I should have added the backport repo and the package might be there ? :thinking:

**Comment by smarlowucf** [comment]
I think for SLES 12 we only provided python2 version of ec2imgutils. @rjschwei can correct me if wrong.

**Comment by apozsuse** [comment]
Closing the issue as the change was merged.
